apiVersion: v1
kind: Pod
metadata:
  name: projected-vol-pod
  labels:
    app: busybox
spec:
  containers:
    - image: busybox
      name: busybox-pod
      command: ['/bin/sh','-c']
      args:
        - sleep 3000
      volumeMounts:
        - name: proje-vol
          mountPath: "/projected-vol"
          readOnly: true

  volumes:
    - name: proje-vol
      projected:
        defaultMode: 0400
        sources:
          - secret: 
              name: db-secret
              items:
                - key: password
                  path: db-secret
          - configMap:
              name: db-conf
              items:
                - key: file1.conf
                  path: db-conf
                  mode: 0777

