apiVersion: v1
kind: Pod
metadata:
  name: projected-vol-pod
  labels:
    app: busybox
spec:
  containers:
    - image: busybox
      name: busybox-pod
      commands: ['/bin/sh','-c']
      args:
        - sleep 3000