apiVersion: v1
kind: Pod
metadata:
  name: projected-vol-pod
  labels:
    app: busybox
spec:
  containers:
    - image: busybox
      name: busybox-pod
      command: ['/bin/sh','-c']
      args:
        - sleep 3000
      volumeMounts:
        - name: proje-vol
          path: "/projected-vol"
          readOnly: true

  volumes:
    - name: proje-vol
      projected:
        defaultMode: 0400
        sources:
          - secret: db-secret
            items:
              - key: db-secret
                path: db-secret
          - configMap:
            items:
              - key: db-conf
                path: db-conf
                mode: 0777

